### ISSUE TITLE
Twitter Hashtag accepted characters

### ISSUE THREAD

**Issue by PixnBits** [BillCruise/BountyBot#1]
From https://twitter.com/BountyBot/status/559047998403932160 it looks that Twitter does not accept hyphens as hashtag characters.

I saw only [one Twitter site result](https://support.twitter.com/articles/370610-my-hashtags-or-replies-aren-t-working) from my Google Grep on official character rules.
(unrelated: it looks like their URL slugger has a similar issue ("aren-t"))

and [the SO question](http://stackoverflow.com/q/14823376/2770309) wasn't too helpful

Nonetheless, [hashify() a](https://github.com/BillCruise/BountyBot/blob/784976abbd61d3cf8d08f1b74147b11f3086f388/tweet_bounty.py#L341) & [hashify() b](https://github.com/BillCruise/BountyBot/blob/784976abbd61d3cf8d08f1b74147b11f3086f388/bounty_bot.py#L227) need\* some character replacement.

*"need" because this is a demo, so obviously it is required have every bell and whistle known to mankind.

**Comment by BillCruise** [comment]
You're right. I always intended to circle back and fix this when I originally wrote that hashify function. I'll see if I can knock it out this weekend.

**Comment by BillCruise** [comment]
I fixed this so that the last step in hashify() will now remove hyphens and capitalize each word in a tag for readability. Thanks for reporting the issue.
